{{ if .linux }}
[".local/bin/antigen.zsh"]
  type = "file"
  url = "https://git.io/antigen"
[".local/bin/starship"]
  type = "archive"
  url = "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
{{ end }}
{{ if .mac }}
[".local/bin/imgcat"]
  type = "file"
  url = "https://iterm2.com/utilities/imgcat"
  executable = true
{{ end }}
