experimental_log_batching_enabled = false
[ui]

[ui.theme]
  dark = "flexoki-dark"
  light = "flexoki-light"

[ui.tracer]
enabled = true

[custom_commands."new change after"]
args = ["new", "--no-edit", "--after", "$change_id"]
description = "Insert a new change after the selected one"

[custom_commands."new change before"]
args = ["new", "--no-edit", "--before", "$change_id"]
description = "Insert a new change before the selected one"
